// RBAC Permission System
// Roles: admin, user, contractor, guest, client
//
// 'client' is the portal role — assigned to authenticated client-portal users.
// Phase 1 keeps this minimal (no admin-side capabilities); Phase 2 fills in
// portal-specific permissions like canViewOwnInvoices, canPayOwnInvoices, etc.

const PERMISSIONS = {
  admin: {
    canViewDashboard: true,
    canViewClients: true,
    canCreateClient: true,
    canEditClient: true,
    canDeleteClient: true,
    canViewProjects: true,
    canCreateProject: true,
    canEditProject: true,
    canDeleteProject: true,
    canViewContractors: true,
    canCreateContractor: true,
    canEditContractor: true,
    canDeleteContractor: true,
    canViewCRM: true,
    canCreateDeal: true,
    canEditDeal: true,
    canDeleteDeal: true,
    canViewInvoices: true,
    canCreateInvoice: true,
    canEditInvoice: true,
    canDeleteInvoice: true,
    canViewProposals: true,
    canCreateProposal: true,
    canEditProposal: true,
    canViewReports: true,
    canViewCalendar: true,
    canCreateEvent: true,
    canViewTime: true,
    canLogTime: true,
    canViewAutomations: true,
    canManageAutomations: true,
    canViewSettings: true,
    canEditSettings: true,
    canManageUsers: true,
    canViewBranding: true,
    canViewAI: true,
  },
  user: {
    canViewDashboard: true,
    canViewClients: true,
    canCreateClient: true,
    canEditClient: true,
    canDeleteClient: false,
    canViewProjects: true,
    canCreateProject: true,
    canEditProject: true,
    canDeleteProject: false,
    canViewContractors: true,
    canCreateContractor: true,
    canEditContractor: true,
    canDeleteContractor: false,
    canViewCRM: true,
    canCreateDeal: true,
    canEditDeal: true,
    canDeleteDeal: false,
    canViewInvoices: true,
    canCreateInvoice: true,
    canEditInvoice: true,
    canDeleteInvoice: false,
    canViewProposals: true,
    canCreateProposal: true,
    canEditProposal: true,
    canViewReports: true,
    canViewCalendar: true,
    canCreateEvent: true,
    canViewTime: true,
    canLogTime: true,
    canViewAutomations: true,
    canManageAutomations: false,
    canViewSettings: true,
    canEditSettings: false,
    canManageUsers: false,
    canViewBranding: true,
    canViewAI: true,
  },
  contractor: {
    canViewDashboard: true,
    canViewClients: false,
    canCreateClient: false,
    canEditClient: false,
    canDeleteClient: false,
    canViewProjects: true,
    canCreateProject: false,
    canEditProject: false,
    canDeleteProject: false,
    canViewContractors: false,
    canCreateContractor: false,
    canEditContractor: false,
    canDeleteContractor: false,
    canViewCRM: false,
    canCreateDeal: false,
    canEditDeal: false,
    canDeleteDeal: false,
    canViewInvoices: false,
    canCreateInvoice: false,
    canEditInvoice: false,
    canDeleteInvoice: false,
    canViewProposals: false,
    canCreateProposal: false,
    canEditProposal: false,
    canViewReports: false,
    canViewCalendar: true,
    canCreateEvent: false,
    canViewTime: true,
    canLogTime: true,
    canViewAutomations: false,
    canManageAutomations: false,
    canViewSettings: false,
    canEditSettings: false,
    canManageUsers: false,
    canViewBranding: true,
    canViewAI: false,
  },
  guest: {
    canViewDashboard: true,
    canViewClients: false,
    canCreateClient: false,
    canEditClient: false,
    canDeleteClient: false,
    canViewProjects: false,
    canCreateProject: false,
    canEditProject: false,
    canDeleteProject: false,
    canViewContractors: false,
    canCreateContractor: false,
    canEditContractor: false,
    canDeleteContractor: false,
    canViewCRM: false,
    canCreateDeal: false,
    canEditDeal: false,
    canDeleteDeal: false,
    canViewInvoices: false,
    canCreateInvoice: false,
    canEditInvoice: false,
    canDeleteInvoice: false,
    canViewProposals: false,
    canCreateProposal: false,
    canEditProposal: false,
    canViewReports: false,
    canViewCalendar: true,
    canCreateEvent: false,
    canViewTime: false,
    canLogTime: false,
    canViewAutomations: false,
    canManageAutomations: false,
    canViewSettings: false,
    canEditSettings: false,
    canManageUsers: false,
    canViewBranding: true,
    canViewAI: false,
  },
  // Portal users have NO admin-app permissions. They are routed away from
  // the admin app entirely (see App.jsx role gate). Portal-specific
  // capabilities (view own projects, pay own invoices, etc.) are checked
  // separately in the client portal pages once Phase 2 lands.
  client: {
    canViewDashboard: false,
    canViewClients: false,
    canCreateClient: false,
    canEditClient: false,
    canDeleteClient: false,
    canViewProjects: false,
    canCreateProject: false,
    canEditProject: false,
    canDeleteProject: false,
    canViewContractors: false,
    canCreateContractor: false,
    canEditContractor: false,
    canDeleteContractor: false,
    canViewCRM: false,
    canCreateDeal: false,
    canEditDeal: false,
    canDeleteDeal: false,
    canViewInvoices: false,
    canCreateInvoice: false,
    canEditInvoice: false,
    canDeleteInvoice: false,
    canViewProposals: false,
    canCreateProposal: false,
    canEditProposal: false,
    canViewReports: false,
    canViewCalendar: false,
    canCreateEvent: false,
    canViewTime: false,
    canLogTime: false,
    canViewAutomations: false,
    canManageAutomations: false,
    canViewSettings: false,
    canEditSettings: false,
    canManageUsers: false,
    canViewBranding: false,
    canViewAI: false,
  },
};

export function can(role, permission) {
  const perms = PERMISSIONS[role || 'guest'];
  return perms ? !!perms[permission] : false;
}

export { PERMISSIONS };
