import { useState, useMemo } from 'react';
import { generateId } from '../data/initialData';

const today = new Date();

const monthNames = [
  'January','February','March','April','May','June',
  'July','August','September','October','November','December',
];
const dayNames = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

const typeColorMap = {
  custom:    'var(--brand)',
  deadline:  'var(--danger)',
  meeting:   'var(--info)',
  milestone: 'var(--success)',
  invoice:   'var(--warning)',
  'follow-up': 'var(--purple)',
};

function getDaysInMonth(year, month) {
  return new Date(year, month + 1, 0).getDate();
}

function getFirstDayOfMonth(year, month) {
  return new Date(year, month, 1).getDay();
}

function pad(n) {
  return String(n).padStart(2, '0');
}

function formatDateKey(year, month, day) {
  return `${year}-${pad(month + 1)}-${pad(day)}`;
}

const emptyEvent = {
  title: '',
  date: '',
  time: '',
  type: 'custom',
  description: '',
};

export default function Calendar({ events, setEvents, projects, invoices }) {
  const [currentMonth, setCurrentMonth] = useState(today.getMonth());
  const [currentYear, setCurrentYear] = useState(today.getFullYear());
  const [selectedDay, setSelectedDay] = useState(today.getDate());
  const [modalOpen, setModalOpen] = useState(false);
  const [editingEvent, setEditingEvent] = useState(null);
  const [form, setForm] = useState({ ...emptyEvent });

  // Auto-generated events from projects and invoices
  const allEvents = useMemo(() => {
    const auto = [];

    if (projects) {
      projects.forEach((p) => {
        if (p.deadline) {
          auto.push({
            id: `auto-proj-${p.id}`,
            title: p.title + ' \u2014 Deadline',
            date: p.deadline,
            type: 'deadline',
            color: 'var(--danger)',
            autoGenerated: true,
          });
        }
      });
    }

    if (invoices) {
      invoices.forEach((inv) => {
        if (inv.dueDate && (inv.status === 'sent' || inv.status === 'overdue')) {
          auto.push({
            id: `auto-inv-${inv.id}`,
            title: 'Invoice ' + inv.invoiceNumber + ' Due',
            date: inv.dueDate,
            type: 'invoice',
            color: 'var(--warning)',
            autoGenerated: true,
          });
        }
      });
    }

    const real = (events || []).map((e) => ({
      ...e,
      color: e.color || typeColorMap[e.type] || 'var(--brand)',
    }));

    return [...real, ...auto];
  }, [events, projects, invoices]);

  // Helpers
  const daysInMonth = getDaysInMonth(currentYear, currentMonth);
  const firstDay = getFirstDayOfMonth(currentYear, currentMonth);
  const selectedDateKey = formatDateKey(currentYear, currentMonth, selectedDay);

  // Build a map of date -> events for the current month for quick lookups
  const eventsByDate = useMemo(() => {
    const map = {};
    allEvents.forEach((ev) => {
      if (!ev.date) return;
      const key = ev.date.slice(0, 10); // YYYY-MM-DD
      if (!map[key]) map[key] = [];
      map[key].push(ev);
    });
    return map;
  }, [allEvents]);

  const dayEvents = eventsByDate[selectedDateKey] || [];

  // Upcoming: events on or after selected day, in the current month, sorted by date
  const upcomingEvents = useMemo(() => {
    return allEvents
      .filter((ev) => ev.date && ev.date.slice(0, 10) > selectedDateKey)
      .sort((a, b) => (a.date > b.date ? 1 : -1))
      .slice(0, 5);
  }, [allEvents, selectedDateKey]);

  // Navigation
  function prevMonth() {
    if (currentMonth === 0) {
      setCurrentMonth(11);
      setCurrentYear((y) => y - 1);
    } else {
      setCurrentMonth((m) => m - 1);
    }
  }

  function nextMonth() {
    if (currentMonth === 11) {
      setCurrentMonth(0);
      setCurrentYear((y) => y + 1);
    } else {
      setCurrentMonth((m) => m + 1);
    }
  }

  function goToday() {
    const now = new Date();
    setCurrentMonth(now.getMonth());
    setCurrentYear(now.getFullYear());
    setSelectedDay(now.getDate());
  }

  // Modal handlers
  function openNewEvent() {
    setEditingEvent(null);
    setForm({ ...emptyEvent, date: selectedDateKey });
    setModalOpen(true);
  }

  function openEditEvent(ev) {
    if (ev.autoGenerated) return;
    setEditingEvent(ev);
    setForm({
      title: ev.title || '',
      date: ev.date || '',
      time: ev.time || '',
      type: ev.type || 'custom',
      description: ev.description || '',
    });
    setModalOpen(true);
  }

  function closeModal() {
    setModalOpen(false);
    setEditingEvent(null);
  }

  function handleFormChange(field, value) {
    setForm((prev) => ({ ...prev, [field]: value }));
  }

  function handleSave() {
    if (!form.title.trim() || !form.date) return;
    if (editingEvent) {
      // Update
      setEvents((prev) =>
        prev.map((e) =>
          e.id === editingEvent.id
            ? { ...e, ...form, color: typeColorMap[form.type] || 'var(--brand)' }
            : e
        )
      );
    } else {
      // Create
      const newEvent = {
        id: generateId(),
        ...form,
        color: typeColorMap[form.type] || 'var(--brand)',
      };
      setEvents((prev) => [...prev, newEvent]);
    }
    closeModal();
  }

  function handleDelete() {
    if (!editingEvent || editingEvent.autoGenerated) return;
    setEvents((prev) => prev.filter((e) => e.id !== editingEvent.id));
    closeModal();
  }

  // Format a date string nicely for display
  function formatDisplayDate(dateStr) {
    if (!dateStr) return '';
    const [y, m, d] = dateStr.split('-').map(Number);
    return `${monthNames[m - 1]} ${d}, ${y}`;
  }

  return (
    <div className="calendar-page page--fill">
      <div className="calendar-layout">
        <div className="calendar-main">
          <div className="calendar-nav">
            <button className="btn btn--ghost btn--sm" onClick={prevMonth}>&larr;</button>
            <h2 className="calendar-month">{monthNames[currentMonth]} {currentYear}</h2>
            <button className="btn btn--ghost btn--sm" onClick={nextMonth}>&rarr;</button>
            <button className="btn btn--ghost btn--sm" onClick={goToday} style={{ marginLeft: 8 }}>
              Today
            </button>
          </div>

          <div className="calendar-grid">
            {dayNames.map((d) => (
              <div key={d} className="calendar-day-name">{d}</div>
            ))}
            {Array.from({ length: firstDay }).map((_, i) => (
              <div key={`e${i}`} className="calendar-cell calendar-cell--empty" />
            ))}
            {Array.from({ length: daysInMonth }).map((_, i) => {
              const day = i + 1;
              const dateKey = formatDateKey(currentYear, currentMonth, day);
              const cellEvents = eventsByDate[dateKey] || [];
              const isToday =
                day === today.getDate() &&
                currentMonth === today.getMonth() &&
                currentYear === today.getFullYear();
              const isSelected = day === selectedDay;

              return (
                <div
                  key={day}
                  className={`calendar-cell${isToday ? ' calendar-cell--today' : ''}${isSelected ? ' calendar-cell--selected' : ''}`}
                  onClick={() => setSelectedDay(day)}
                >
                  <span className="calendar-cell-num">{day}</span>
                  {cellEvents.length > 0 && (
                    <div className="calendar-cell-dots">
                      {cellEvents.slice(0, 3).map((ev, idx) => (
                        <span
                          key={idx}
                          className="calendar-cell-dot"
                          style={{ background: ev.color }}
                        />
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        <div className="calendar-sidebar">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <h3 className="calendar-sidebar-title">
              {monthNames[currentMonth]} {selectedDay}
            </h3>
            <button className="btn btn--brand btn--sm" onClick={openNewEvent}>
              + New Event
            </button>
          </div>

          {dayEvents.length === 0 ? (
            <div className="calendar-empty">No events scheduled</div>
          ) : (
            <div className="calendar-events">
              {dayEvents.map((ev) => (
                <div
                  key={ev.id}
                  className={`calendar-event${!ev.autoGenerated ? ' calendar-event--clickable' : ''}`}
                  onClick={() => openEditEvent(ev)}
                  style={!ev.autoGenerated ? { cursor: 'pointer' } : undefined}
                >
                  <div className="calendar-event-dot" style={{ background: ev.color }} />
                  <div>
                    <div className="calendar-event-title">{ev.title}</div>
                    <div className="calendar-event-time">
                      {ev.time || 'All Day'}
                      {ev.autoGenerated && (
                        <span style={{ marginLeft: 8, opacity: 0.5, fontSize: '0.8em' }}>Auto</span>
                      )}
                    </div>
                    {ev.description && (
                      <div className="calendar-event-desc" style={{ opacity: 0.7, fontSize: '0.85em' }}>
                        {ev.description}
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          <h4 className="calendar-sidebar-subtitle">Upcoming</h4>
          <div className="calendar-events">
            {upcomingEvents.length === 0 ? (
              <div className="calendar-empty">No upcoming events</div>
            ) : (
              upcomingEvents.map((ev) => (
                <div
                  key={ev.id}
                  className="calendar-event calendar-event--upcoming"
                  onClick={() => {
                    // Navigate to the event's date
                    const [y, m, d] = ev.date.split('-').map(Number);
                    setCurrentYear(y);
                    setCurrentMonth(m - 1);
                    setSelectedDay(d);
                  }}
                >
                  <div className="calendar-event-dot" style={{ background: ev.color }} />
                  <div>
                    <div className="calendar-event-title">{ev.title}</div>
                    <div className="calendar-event-time">
                      {formatDisplayDate(ev.date)} &middot; {ev.time || 'All Day'}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Add / Edit Event Modal */}
      {modalOpen && (
        <div className="modal-overlay" onClick={closeModal}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal__header">
              <h2>{editingEvent ? 'Edit Event' : 'New Event'}</h2>
              <button className="btn btn--ghost btn--sm" onClick={closeModal}>&times;</button>
            </div>
            <div className="modal__body">
              <label className="form-label">Title</label>
              <input
                className="form-input"
                type="text"
                value={form.title}
                onChange={(e) => handleFormChange('title', e.target.value)}
                placeholder="Event title"
              />

              <label className="form-label" style={{ marginTop: 12 }}>Date</label>
              <input
                className="form-input"
                type="date"
                value={form.date}
                onChange={(e) => handleFormChange('date', e.target.value)}
              />

              <label className="form-label" style={{ marginTop: 12 }}>Time</label>
              <input
                className="form-input"
                type="time"
                value={form.time}
                onChange={(e) => handleFormChange('time', e.target.value)}
              />

              <label className="form-label" style={{ marginTop: 12 }}>Type</label>
              <select
                className="form-input"
                value={form.type}
                onChange={(e) => handleFormChange('type', e.target.value)}
              >
                <option value="custom">Custom</option>
                <option value="meeting">Meeting</option>
                <option value="milestone">Milestone</option>
                <option value="follow-up">Follow-up</option>
              </select>

              <label className="form-label" style={{ marginTop: 12 }}>Description</label>
              <textarea
                className="form-input"
                rows={3}
                value={form.description}
                onChange={(e) => handleFormChange('description', e.target.value)}
                placeholder="Optional description"
              />
            </div>
            <div className="modal__footer">
              {editingEvent && (
                <button className="btn btn--danger btn--sm" onClick={handleDelete}>
                  Delete
                </button>
              )}
              <div style={{ flex: 1 }} />
              <button className="btn btn--ghost btn--sm" onClick={closeModal}>
                Cancel
              </button>
              <button className="btn btn--brand btn--sm" onClick={handleSave}>
                {editingEvent ? 'Save Changes' : 'Create Event'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
